### ISSUE TITLE
"Paste entry list" does not work

### ISSUE THREAD

**Issue by badonyx** [friedger/stacks-send-many#26]
1) I cannot paste into the form. 
2) Manually entering entries does not seem to do anything.
3) Force-pasting (in csv format) converts newlines to spaces and still does not seem to do anything.

**Comment by friedger** [comment]
This is working in the current version. Please feel free to open a new issue if you still have problems to paste entries.

**Comment by badonyx** [comment]
It does not work...

```
index-CbOijsge.js:674 Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
    at index-CbOijsge.js:674:85
    at Array.map (<anonymous>)
    at C (index-CbOijsge.js:674:25)
    at Object.cK (index-CbOijsge.js:37:9864)
    at lK (index-CbOijsge.js:37:10018)
    at fK (index-CbOijsge.js:37:10075)
    at o8 (index-CbOijsge.js:37:31462)
    at UB (index-CbOijsge.js:37:31879)
    at index-CbOijsge.js:37:36792
    at xA (index-CbOijsge.js:40:36957)
```
